version: "3.8"

services:
  # https://hub.docker.com/_/elasticsearch/
  es01:
    image: elasticsearch:8.3.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  cerebro:
    image: lmenezes/cerebro:0.9.4
    ports:
      - 9000:9000
    environment:
      HOSTS: |
        ES1,http://es01:9200

volumes:
  data01:
    driver: local
