version: "3"

tasks:
  default:
    cmds: [{ task: help }]

  help:
    desc: Show this help.
    cmds: [task -l]

  op:
    desc: |
      Usage: task op title='my-service' notes='https://my-service.example.com/account/api-keys' key=api-key
    cmds:
      - |
        read -p 'value> ' value
        op item create --vault dotenv --category 'Secure Note' --title {{.title}} 'notesPlain={{.notes}}' "{{.key}}=${value}"
