version: "3.8"

# https://www.elastic.co/guide/en/elasticsearch/reference/8.3/docker.html

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=sandbox
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    volumes:
      - data02:/usr/share/elasticsearch/data
    environment:
      - node.name=es02
      - cluster.name=sandbox
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    volumes:
      - data03:/usr/share/elasticsearch/data
    environment:
      - node.name=es03
      - cluster.name=sandbox
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1

  cerebro:
    image: lmenezes/cerebro:0.9.4
    ports:
      - 9000:9000
    environment:
      HOSTS: |
        ES1,http://es01:9200
        ES2,http://es02:9200
        ES3,http://es03:9200

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
