CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  slug VARCHAR NOT NULL UNIQUE,
  password_digest VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
