version: "3"

tasks:
  setup:
    cmds:
      - docker compose up -d

  run:
    cmds:
      - |
        set -xe

        [ -e movies.json ] || curl -sSLO https://www.meilisearch.com/movies.json

        cat movies.json | http -v POST 'http://localhost:7700/indexes/movies/documents?primaryKey=id'

        echo '{"q": "botman"}' | http -v POST 'http://localhost:7700/indexes/movies/search'

  destroy:
    cmds:
      - docker compose down
