[tasks.env]
script = '''
aws_region=ap-northeast-1
aws_account_id=$(aws sts get-caller-identity | jq -r .Account)

echo > .env
echo "AWS_REGION=${aws_region}" >> .env
echo "AWS_ACCOUNT_ID=${aws_account_id}" >> .env
echo "DOCKER_SERVER=${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com" >> .env
'''

[tasks.login]
script = '''
aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin "${DOCKER_SERVER}"
'''
env_files = [".env"]

[tasks.push]
script = '''
env KO_DOCKER_REPO=$DOCKER_SERVER ko build --preserve-import-paths --sbom=none .
'''
env_files = [".env"]

[tasks.deploy]
script = '''
terraform apply -auto-approve

terraform output -json | jq -r 'to_entries[] | "TF_OUTPUT_\(.key)=\(.value.value)"' >> .tfoutput.env
'''

[tasks.load-testing]
cwd = "k6"
script = '''
k6 run --vus 20 --duration 30s script.js
'''
env_files = [".tfoutput.env"]
