version: "3"

tasks:
  setup:
    cmds:
      - docker compose up -d

  run:
    cmds:
      - |
        set -e

        http -v http://localhost:9200/_cluster/health

        http -v http://localhost:9200/my-index

        http -v PUT http://localhost:9200/my-index/_doc/1 'content-type: application/json' \
          title="Sample Document", \
          content="This is a sample document."

        http -v http://localhost:9200/my-index/_doc/1

        http -v POST http://localhost:9200/my-index/_search 'content-type: application/json' \
          query:='{"match": {"content": "sample"}}'

  run-semantic-search:
    # https://www.elastic.co/jp/blog/may-2023-launch-sparse-encoder-ai-model
    # https://www.elastic.co/jp/blog/whats-new-elastic-enterprise-search-8-8-0
    # https://www.elastic.co/guide/en/machine-learning/8.8/ml-nlp-elser.html
    cmds:
      - |
        set -ex
        cat semantic-search/mappings.json | http -v PUT http://localhost:9200/semantic-search
        cat semantic-search/pipeline.json | http -v PUT http://localhost:9200/_ingest/pipeline/elser-v1-test
        cat semantic-search/document.json | http -v PUT http://localhost:9200/my-index/_doc/1
        cat semantic-search/query.json | http -v POST http://localhost:9200/my-index/_search

  clean:
    cmds:
      - docker compose down
