version: "3"

env:
  PROJECT_ID:
    sh: gcloud config get-value project

tasks:
  setup:
    cmds:
      - poetry install

  run:
    cmds:
      - poetry run python python_google_cloud/main.py {{.CLI_ARGS}}
