#!/bin/bash

set -xeuo pipefail

build() {
  [ "${SKIP_BUILD:-false}" = true ] && return

  cd "$REPOSITORY_ROOT/application"

  npm ci
  npm run build
}

deploy() {
  cd "$REPOSITORY_ROOT/infrastructure"

  if ! aws --region "${AWS_REGION:?}" s3 ls "s3://${TF_BACKEND_BUCKET:?}"; then
    aws --region "${AWS_REGION:?}" s3 mb "s3://${TF_BACKEND_BUCKET:?}"
  fi

  terraform init \
    -backend-config="bucket=${TF_BACKEND_BUCKET:?}" \
    -backend-config="key=${TF_BACKEND_KEY:?}" \
    -backend-config="region=${AWS_REGION:?}"

  tflint

  terraform fmt -check=true -write=false -diff=true
  terraform validate
  terraform apply -auto-approve
}

hotswap() {
  [ "${SKIP_HOTSWAP:-false}" = true ] && return

  cd "$REPOSITORY_ROOT"

  watchexec -w application -- 'time ./script/_hotswap && echo "Wait file changes.."'
}

build
deploy
hotswap
