version: "3"

env:
  TFSTATE_BUCKET:
    sh: op read op://sandbox/terraform/gcs-backend-bucket
  TFSTATE_PREFIX:
    sh: basename $PWD
  TF_VAR_project_id:
    sh: gcloud config get-value project

tasks:
  deploy:
    dir: terraform/
    cmds:
      - |
        terraform init \
          -backend-config="bucket=${TFSTATE_BUCKET}" \
          -backend-config="prefix=${TFSTATE_PREFIX}"
      - terraform apply -auto-approve

  ssh:
    env:
      INSTANCE_NAME:
        sh: terraform output -raw instance_name
    dir: terraform/
    cmds:
      - gcloud compute config-ssh --remove
      - gcloud compute config-ssh
      - gcloud compute ssh $INSTANCE_NAME

  start:
    env:
      INSTANCE_NAME:
        sh: terraform output -raw instance_name
    dir: terraform/
    cmds:
      - gcloud compute instances start $INSTANCE_NAME

  stop:
    env:
      INSTANCE_NAME:
        sh: terraform output -raw instance_name
    dir: terraform/
    cmds:
      - gcloud compute instances stop $INSTANCE_NAME

  destroy:
    dir: terraform/
    cmds:
      - terraform destroy -auto-approve
