version: "3"

env:
  TFSTATE_BUCKET:
    sh: op read op://sandbox/terraform/gcs-backend-bucket
  TFSTATE_PREFIX:
    sh: basename $PWD
  TF_VAR_project_id:
    sh: gcloud config get-value project

tasks:
  deploy:
    cmds:
      - |
        terraform init \
          -backend-config="bucket=${TFSTATE_BUCKET}" \
          -backend-config="prefix=${TFSTATE_PREFIX}"
      - terraform apply -auto-approve

  destroy:
    cmds:
      - terraform destroy -auto-approve
