version: "3"

env:
  AWS_CONFIG_FILE: "{{.USER_WORKING_DIR}}/.aws"
  AWS_PROFILE: sandbox

tasks:
  setup:
    cmds:
      - poetry install
      - op read op://sandbox/aws/notesPlain >.aws

  run:
    cmds:
      - poetry run python python_aws/main.py {{.CLI_ARGS}}
