version: "3"

dotenv: [.env]

tasks:
  setup:
    cmds:
      - |
        echo '
        API_KEY=op://sandbox/microcms-lambdasawa-test/api-key
        ' | op inject >.env

  run:
    cmds:
      - |
        http -v "https://lambdasawa-test.microcms.io/api/v1/test" "x-microcms-api-key: $API_KEY"
