version: "3"

env:
  AWS_CONFIG_FILE: "{{.USER_WORKING_DIR}}/.aws"
  AWS_PROFILE: sandbox

tasks:
  setup:
    cmds:
      - op read op://dotenv/aws/notesPlain >.aws

  run:
    cmds:
      - aws s3 ls
