version: "3"

env:
  AWS_CONFIG_FILE: "{{.USER_WORKING_DIR}}/.aws"
  AWS_PROFILE: sandbox
  TFSTATE_BUCKET:
    sh: op read op://sandbox/terraform/s3-backend-bucket
  TFSTATE_KEY:
    sh: echo $(basename $PWD)/terraform.tfstate

tasks:
  setup:
    cmds:
      - op read op://sandbox/aws/notesPlain >.aws

  deploy:
    cmds:
      - |
        terraform init \
          -backend-config="bucket=${TFSTATE_BUCKET}" \
          -backend-config="key=${TFSTATE_KEY}" \
          -backend-config="region=ap-northeast-1"
      - terraform apply -auto-approve

  destroy:
    cmds:
      - terraform destroy -auto-approve
